CREATE TABLE IF NOT EXISTS email_text (
    id UUID PRIMARY KEY,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_send_email (
    id UUID PRIMARY KEY,
    email_text_id UUID NOT NULL,
    email VARCHAR(100) NOT NULL,
    send_status BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);